export type Field={key:string,label:string,type?:'text'|'email'|'number'|'date'|'textarea'|'select'|'boolean',required?:boolean,options?:string[],relation?:string,min?:number,max?:number,step?:string};
export type Module={table:string,title:string,description:string,fields:Field[]};
const name:Field={key:'name',label:'Name',required:true};
const contact:Field[]=[{key:'email',label:'Email',type:'email'},{key:'phone',label:'Phone'}];
const notes:Field={key:'notes',label:'Notes',type:'textarea'};
const active:Field={key:'active',label:'Active',type:'boolean'};
const assign:Field={key:'assigned_user',label:'Assigned user',relation:'members'};
const customer:Field={key:'customer_id',label:'Customer',relation:'customers'};
const priority:Field={key:'priority',label:'Priority',type:'select',options:['MEDIUM','LOW','HIGH','URGENT']};
export const modules:Record<string,Module>={
 shipments:{table:'shipments',title:'Dispatch & delivery',description:'Track carriers and delivery proof against approved sales orders. Dispatch the sales order before recording in-transit or delivered status.',fields:[name,{key:'order_id',label:'Sales order',relation:'business_documents',required:true},{key:'carrier',label:'Carrier'},{key:'tracking_number',label:'Tracking number'},{key:'vehicle_number',label:'Vehicle number'},{key:'driver_contact',label:'Driver contact'},{key:'status',label:'Delivery status',type:'select',options:['PLANNED','IN_TRANSIT','DELIVERED','EXCEPTION']},{key:'expected_on',label:'Expected delivery',type:'date'},{key:'delivered_on',label:'Delivered on',type:'date'},{key:'proof_reference',label:'Proof of delivery reference'},notes]},
 customers:{table:'customers',title:'Customers & dealers',description:'Customer contacts, delivery addresses, account ownership and credit terms.',fields:[name,{key:'customer_type',label:'Customer type',type:'select',options:['CUSTOMER','FARM','DEALER','DISTRIBUTOR','CORPORATE']},...contact,{key:'address',label:'Address',type:'textarea'},{key:'gstin',label:'GSTIN'},{key:'state_code',label:'State code'},{key:'territory',label:'Territory'},{key:'credit_limit',label:'Credit limit (INR)',type:'number',min:0},{key:'payment_days',label:'Payment terms (days)',type:'number',min:0,max:365,step:'1'},assign,notes,active]},
 leads:{table:'leads',title:'Lead pipeline',description:'Track enquiries, stages, follow-ups and customer conversion. Link a customer when marking a lead converted.',fields:[name,...contact,{key:'source',label:'Source'},{key:'stage',label:'Stage',type:'select',options:['NEW','CONTACTED','QUALIFIED','PROPOSAL','NEGOTIATION','CONVERTED','LOST']},{key:'expected_value',label:'Expected value (INR)',type:'number',min:0},{key:'next_follow_up',label:'Next follow-up',type:'date'},{key:'location',label:'Location'},{key:'species',label:'Species'},{key:'requirement',label:'Requirement',type:'textarea'},assign,customer,notes]},
 activities:{table:'lead_activities',title:'CRM activities',description:'Record calls, meetings and follow-up notes. Recording an email or WhatsApp activity does not send a message.',fields:[name,{key:'lead_id',label:'Lead',relation:'leads',required:true},{key:'activity_type',label:'Type',type:'select',options:['CALL','MEETING','EMAIL','WHATSAPP','NOTE']},{key:'occurred_on',label:'Activity date',type:'date',required:true},notes]},
 products:{table:'products',title:'Product catalog',description:'Maintain SKUs, units, prices and product tax rates. Draft documents use the catalog prices when saved.',fields:[name,{key:'sku',label:'SKU',required:true},{key:'category',label:'Category'},{key:'unit',label:'Unit',required:true},{key:'hsn_sac',label:'HSN / SAC'},{key:'packaging',label:'Packaging'},{key:'description',label:'Description',type:'textarea'},{key:'unit_price',label:'Selling price (INR)',type:'number',min:0},{key:'cost',label:'Purchase cost (INR)',type:'number',min:0},{key:'gst_rate',label:'GST rate (%)',type:'number',min:0,max:100},{key:'reorder_point',label:'Reorder point',type:'number',min:0},active]},
 suppliers:{table:'suppliers',title:'Suppliers',description:'Supplier contacts and purchasing terms.',fields:[name,...contact,{key:'address',label:'Address',type:'textarea'},{key:'gstin',label:'GSTIN'},{key:'payment_days',label:'Payment terms (days)',type:'number',min:0,max:365,step:'1'},notes,active]},
 warehouses:{table:'warehouses',title:'Warehouses',description:'Stock locations used by orders, purchases and adjustments.',fields:[name,{key:'code',label:'Warehouse code',required:true},{key:'address',label:'Address',type:'textarea'},active]},
 tasks:{table:'business_tasks',title:'Assigned tasks',description:'Admins assign and maintain tasks. Employees can view their assignments and report progress in Daily work.',fields:[name,{key:'description',label:'Description',type:'textarea'},assign,{key:'due_date',label:'Due date',type:'date'},{key:'status',label:'Status',type:'select',options:['OPEN','IN_PROGRESS','BLOCKED','DONE','CANCELLED']},priority]},
 expenses:{table:'expenses',title:'Expenses',description:'Record operating expenses separately from supplier payments to avoid double counting.',fields:[name,{key:'amount',label:'Amount (INR)',type:'number',min:0.01,required:true},{key:'expense_date',label:'Expense date',type:'date',required:true},{key:'category',label:'Category'},{key:'reference',label:'Reference'},notes]},
 support:{table:'support_tickets',title:'Support tickets',description:'Track customer issues, priorities and resolution status.',fields:[name,customer,{key:'description',label:'Description',type:'textarea'},{key:'status',label:'Status',type:'select',options:['OPEN','IN_PROGRESS','RESOLVED','CLOSED']},priority]},
};
export const documentKinds:Record<string,{kind:string,title:string}>={quotes:{kind:'QUOTE',title:'Quotations'},orders:{kind:'ORDER',title:'Sales orders'},purchases:{kind:'PURCHASE',title:'Purchase orders'},invoices:{kind:'INVOICE',title:'Invoices'}};
export const money=(value:unknown)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(value||0));
