import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {membership} from '@/lib/auth';
import {money} from '@/lib/operations/config';
import {PortalOrderForm} from '@/components/portal-order-form';
import {submitRequest,reorderRequest} from './actions';
export const dynamic='force-dynamic';
export default async function Requests({searchParams}:{searchParams:Promise<{page?:string,q?:string,error?:string,saved?:string}>}){
 const a=await membership(),s=await searchParams;const page=Math.max(1,Math.min(10000,Math.floor(Number(s.page)||1)));
 const [account,catalog,requests]=await Promise.all([a.db.rpc('portal_customer_id',{org_id:a.organizationId}),a.db.rpc('portal_catalog',{org_id:a.organizationId,terms:(s.q||'').slice(0,100),page_number:1}),a.db.from('portal_requests').select('*',{count:'exact'}).eq('organization_id',a.organizationId).order('created_at',{ascending:false}).range((page-1)*30,page*30-1)]);
 if(!account.data)return <main className="content"><h1>Portal access required</h1><Link href="/portal">Back to your account</Link></main>;
 if(catalog.error||requests.error)throw new Error('Unable to load requests.');
 return <main className="content" style={{margin:'auto'}}><header><p className="eyebrow">SPRINGPOOL PORTAL</p><h1>Orders & requests</h1><Link href="/portal">← Account and documents</Link></header>{s.error&&<p className="notice" role="alert">{s.error}</p>}{s.saved&&<p className="notice" role="status">Request received. SpringPool will review it.</p>}<section className="panel"><h2>Place an order request</h2><form method="get" className="inline-form"><label>Find products<input name="q" maxLength={100} defaultValue={s.q}/></label><button>Search</button></form><p>Showing up to 30 matching products. Search by product name or SKU to narrow the selection.</p><PortalOrderForm products={catalog.data} requestKey={randomUUID()}/></section><details className="panel"><summary>Support or payment reference</summary><form action={submitRequest} className="form-grid"><input name="key" type="hidden" value={randomUUID()}/><label>Request type<select name="kind"><option value="SUPPORT">Support request</option><option value="PAYMENT">Payment reference</option></select></label><label>Subject / invoice number<input name="title" required minLength={2} maxLength={160}/></label><label>Details<textarea name="body" required maxLength={2000}/></label><p>For payments, include the transfer reference, amount, date and invoice number. This does not mark an invoice paid; an administrator must verify and record the payment.</p><button>Submit request</button></form></details><section className="panel"><h2>Your requests</h2><p>{requests.count||0} requests · Page {page}</p>{requests.data.map(r=><details key={r.id}><summary>{r.subject} · {r.kind} · {r.status}</summary><p>Reference: {r.id}</p><p>{r.details}</p>{r.kind==='ORDER'&&<><p>Estimated total at submission: {money(r.estimated_total)}</p><ul>{r.items.map((l:{product_id:string,name:string,quantity:number,unit:string})=><li key={l.product_id}>{l.name}: {l.quantity} {l.unit}</li>)}</ul><form action={reorderRequest}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="key" value={randomUUID()}/><button className="secondary">Request same items at current prices</button></form></>}{r.admin_reply&&<p><strong>SpringPool response:</strong> {r.admin_reply}</p>}{r.document_id&&<p>An ERP draft has been created. Your confirmed order will appear in your account after approval.</p>}</details>)}{!requests.data.length&&<p>No requests submitted yet.</p>}<div className="inline-form">{page>1&&<Link href={`?page=${page-1}`}>Previous</Link>}{page*30<(requests.count||0)&&<Link href={`?page=${page+1}`}>Next</Link>}</div></section></main>;
}
