import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
test('operations enforce admin authority, tenant boundaries, stock, credit, invoice snapshots and payment limits',async()=>{
 const db=new PGlite();const org='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',admin='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',employee='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',sales='cccccccc-cccc-4ccc-8ccc-cccccccccccc',foreign='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
 const customer='11111111-aaaa-4111-8111-111111111111',supplier='11111111-bbbb-4111-8111-111111111111',product='11111111-cccc-4111-8111-111111111111',warehouse='11111111-dddd-4111-8111-111111111111';
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
 for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync('supabase/migrations/'+f,'utf8'));
 await db.exec(`insert into auth.users values('${admin}','admin@test.invalid'),('${employee}','employee@test.invalid'),('${sales}','sales@test.invalid'),('${foreign}','foreign@test.invalid');insert into public.organizations(id,name) values('${org}','Test org'),('${other}','Other org');insert into public.organization_members(organization_id,user_id,role_code) values('${org}','${admin}','ADMIN'),('${org}','${employee}','EMPLOYEE'),('${org}','${sales}','SALES_EXECUTIVE'),('${other}','${foreign}','ADMIN');select set_config('request.jwt.claim.sub','${admin}',false);insert into public.company_settings(organization_id,display_name,legal_name,registered_address,gstin) values('${org}','Test company','Test company legal','Test address','27ABCDE1234F1Z5');set role authenticated;`);
 assert.equal((await db.query(`select * from public.admin_members('${org}')`)).rows.length,3);
 await assert.rejects(db.exec(`select public.admin_set_member('${org}','admin@test.invalid','EMPLOYEE',true)`),/last administrator/);
 await assert.rejects(db.exec(`select public.admin_set_member('${org}','foreign@test.invalid','EMPLOYEE',true)`),/another workspace/);
 await db.exec(`reset role;insert into public.customers(id,organization_id,name,address,credit_limit,assigned_user) values('${customer}','${org}','Customer','Delivery address',5000,'${sales}');insert into public.suppliers(id,organization_id,name) values('${supplier}','${org}','Supplier');insert into public.products(id,organization_id,name,sku,category,unit,unit_price,cost,gst_rate) values('${product}','${org}','Product','P1','Feed','kg',100,50,18);insert into public.warehouses(id,organization_id,name,code) values('${warehouse}','${org}','Main warehouse','MAIN');set role authenticated;`);
 await db.exec(`insert into public.customers(organization_id,name) values('${org}','Second customer');update public.customers set phone='123' where name='Second customer';`);
 await assert.rejects(db.exec(`insert into public.leads(organization_id,name,stage) values('${org}','Invalid conversion','CONVERTED')`));
 await assert.rejects(db.exec(`insert into public.customers(organization_id,name,assigned_user) values('${org}','Cross tenant','${foreign}')`));
 await db.exec(`select set_config('request.jwt.claim.sub','${employee}',false)`);
 assert.equal((await db.query('select * from public.customers')).rows.length,0);
 await assert.rejects(db.exec(`insert into public.products(organization_id,name,sku,unit) values('${org}','Forged','P2','kg')`));
 await assert.rejects(db.exec(`select public.admin_members('${org}')`));
 await assert.rejects(db.exec(`select public.admin_set_member('${org}','employee@test.invalid','ADMIN',true)`));
 await assert.rejects(db.exec(`select public.record_stock_change('${org}','${warehouse}','${product}',100,'Forged stock')`));
 await db.exec(`select set_config('request.jwt.claim.sub','${sales}',false)`);assert.equal((await db.query('select * from public.customers')).rows.length,1);
 assert.equal((await db.query(`update public.customers set name='Forged' returning id`)).rows.length,0);
 await db.exec(`select set_config('request.jwt.claim.sub','${admin}',false);select public.record_stock_change('${org}','${warehouse}','${product}',10,'Opening inventory');`);
 const save=async(kind:string,qty:number,existing:string|null=null)=>{const r=await db.query<{id:string}>(`select public.save_business_document($1,$2,$3,$4,$5,'27',null,'Test document',$6::jsonb) id`,[org,existing,kind,kind==='PURCHASE'?supplier:customer,warehouse,JSON.stringify([{product_id:product,quantity:qty,unit_price:0,tax:0}])]);return r.rows[0].id;};
 const state=async(id:string,command:string)=>(await db.query<{id:string}>('select public.change_document_state($1,$2,$3) id',[org,id,command])).rows[0].id;
 const order=await save('ORDER',4);const doc=(await db.query<{grand_total:string,subtotal:string}>('select * from public.business_documents where id=$1',[order])).rows[0];assert.equal(Number(doc.grand_total),472);assert.equal(Number(doc.subtotal),400);
 await state(order,'APPROVE');assert.equal(Number((await db.query<{reserved:string}>('select reserved from public.stock_balances')).rows[0].reserved),4);
 await assert.rejects(save('ORDER',3,order),/Only drafts/);await assert.rejects(db.exec('update public.business_documents set grand_total=0'));
 const oversell=await save('ORDER',7);await assert.rejects(state(oversell,'APPROVE'),/Insufficient/);await state(oversell,'CANCEL');
 const credit=await save('ORDER',50);await assert.rejects(state(credit,'APPROVE'),/credit limit/);
 const cancel=await save('ORDER',2);await state(cancel,'APPROVE');await state(cancel,'CANCEL');assert.equal(Number((await db.query<{reserved:string}>('select reserved from public.stock_balances')).rows[0].reserved),4);
 await state(order,'DISPATCH');await assert.rejects(state(order,'DISPATCH'),/Invalid state/);assert.equal(Number((await db.query<{quantity:string}>('select quantity from public.stock_balances')).rows[0].quantity),6);
 const invoice=await state(order,'INVOICE');await assert.rejects(state(order,'INVOICE'));
 await db.exec(`update public.customers set name='Changed customer' where id='${customer}'`);const inv=(await db.query<{buyer_snapshot:{name:string},cgst:string,sgst:string,igst:string}>('select * from public.business_documents where id=$1',[invoice])).rows[0];assert.equal(inv.buyer_snapshot.name,'Customer');assert.equal(Number(inv.cgst),36);assert.equal(Number(inv.sgst),36);assert.equal(Number(inv.igst),0);
 await db.query(`select public.record_document_payment($1,$2,200,'BANK_TRANSFER','TEST-1',current_date)`,[org,invoice]);await assert.rejects(db.query(`select public.record_document_payment($1,$2,300,'CASH','TEST-2',current_date)`,[org,invoice]),/exceeds/);await db.query(`select public.record_document_payment($1,$2,272,'CASH','TEST-3',current_date)`,[org,invoice]);
 const purchase=await save('PURCHASE',5);await state(purchase,'APPROVE');await state(purchase,'RECEIVE');await assert.rejects(state(purchase,'RECEIVE'));assert.equal(Number((await db.query<{quantity:string}>('select quantity from public.stock_balances')).rows[0].quantity),11);
 const quote=await save('QUOTE',1);const converted=await state(quote,'ACCEPT');assert.ok(converted);await assert.rejects(state(quote,'ACCEPT'));
 await db.query(`insert into public.shipments(organization_id,name,order_id,status) values($1,'Delivery record',$2,'IN_TRANSIT')`,[org,order]);
 await assert.rejects(db.query(`update public.shipments set status='DELIVERED' where order_id=$1`,[order]));
 await db.query(`update public.shipments set status='DELIVERED',delivered_on=current_date,proof_reference='Signed receipt TEST' where order_id=$1`,[order]);
 await assert.rejects(db.query(`insert into public.shipments(organization_id,name,order_id,status) values($1,'Invalid shipment',$2,'IN_TRANSIT')`,[org,converted]));
 const output=(await db.query<{id:string}>(`insert into public.products(organization_id,name,sku,category,unit,unit_price,gst_rate) values($1,'Finished feed','FINISHED','Feed','kg',150,18) returning id`,[org])).rows[0].id;
 const produce=(batch:string,quantity:number)=>db.query(`select public.post_production($1,$2,$3,2,$4,current_date,null,'Test production',$5::jsonb)`,[org,warehouse,output,batch,JSON.stringify([{product_id:product,quantity}])]);
 await produce('BATCH-TEST-1',3);await assert.rejects(produce('BATCH-TEST-1',3));
 assert.equal(Number((await db.query<{quantity:string}>('select quantity from public.stock_balances where product_id=$1',[product])).rows[0].quantity),8);
 assert.equal(Number((await db.query<{quantity:string}>('select quantity from public.stock_balances where product_id=$1',[output])).rows[0].quantity),2);
 await assert.rejects(produce('BATCH-TEST-FAIL',100),/Insufficient/);
 assert.equal((await db.query('select * from public.production_runs')).rows.length,1);
 await assert.rejects(db.query(`select public.record_document_payment($1,$2,1,'CASH','TEST-3',current_date)`,[org,invoice]));
 await db.exec(`select set_config('request.jwt.claim.sub','${foreign}',false)`);assert.equal((await db.query('select * from public.business_documents')).rows.length,0);await assert.rejects(state(order,'DELIVER'));
 await db.exec(`select set_config('request.jwt.claim.sub','${admin}',false)`);await db.exec(`select public.admin_set_member('${org}','employee@test.invalid','HR_MANAGER',true);select set_config('request.jwt.claim.sub','${employee}',false);`);assert.equal((await db.query<{allowed:boolean}>(`select public.has_permission('${org}','staff.manage') allowed`)).rows[0].allowed,false);
 await db.exec('reset role');assert.ok((await db.query('select * from public.audit_logs')).rows.length>20);await db.exec('set role anon');await assert.rejects(db.query('select * from public.customers'));await assert.rejects(state(order,'DELIVER'));
 }finally{await db.close();}
});
