import Link from 'next/link';
import {Workspace} from '@/components/workspace';
import {operationsAccess} from '@/lib/operations/access';
import {documentChoices} from '@/lib/operations/choices';
import {adjustStock} from '@/app/sales/actions';
export const dynamic='force-dynamic';
export default async function Inventory({searchParams}:{searchParams:Promise<{error?:string,saved?:string,page?:string}>}){const a=await operationsAccess();const s=await searchParams;const page=Math.max(1,Math.min(10000,Number(s.page)||1));const [balances,movements]=await Promise.all([a.db.from('stock_balances').select('*,products(name,sku,reorder_point),warehouses(name)',{count:'exact'}).eq('organization_id',a.organizationId).order('product_id').range((page-1)*50,page*50-1),a.db.from('stock_movements').select('*,products(name),warehouses(name)').eq('organization_id',a.organizationId).order('created_at',{ascending:false}).limit(50)]);if(balances.error||movements.error)throw new Error('Unable to load inventory.');const choices=a.admin?await documentChoices(a,'ORDER'):null;
 return <Workspace email={a.user.email}><header><p className="eyebrow">WAREHOUSE</p><h1>Inventory</h1><p>Available stock excludes quantities reserved by approved sales orders.</p><Link href="/records/warehouses">Manage warehouses →</Link></header>{s.error&&<p className="notice" role="alert">{s.error}</p>}{s.saved&&<p role="status">Stock adjustment recorded.</p>}{choices&&<details className="panel"><summary>Opening stock / adjustment</summary><form action={adjustStock} className="form-grid"><label>Warehouse<select name="warehouse" required><option value="">Select warehouse</option>{choices.warehouses.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></label><label>Product<select name="product" required><option value="">Select product</option>{choices.products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Quantity change (+ / −)<input type="number" step="0.001" name="delta" required/></label><label>Reason<input name="reason" minLength={5} maxLength={500} required/></label><button>Post stock adjustment</button></form></details>}<section className="panel"><h2>Stock balances</h2><p>{balances.count||0} balances · Page {page}</p><div className="table-wrap"><table><thead><tr><th>Product</th><th>Warehouse</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Reorder</th></tr></thead><tbody>{balances.data?.map(b=><tr key={b.warehouse_id+b.product_id}><td>{b.products?.name}<br/><small>{b.products?.sku}</small></td><td>{b.warehouses?.name}</td><td>{b.quantity}</td><td>{b.reserved}</td><td>{Number(b.quantity)-Number(b.reserved)}</td><td>{Number(b.quantity)-Number(b.reserved)<=Number(b.products?.reorder_point)?'Low stock':'—'}</td></tr>)}</tbody></table></div>{!balances.data?.length&&<p>No stock balances available.</p>}<div className="inline-form">{page>1&&<Link href={'?page='+(page-1)}>Previous</Link>}{page*50<(balances.count||0)&&<Link href={'?page='+(page+1)}>Next</Link>}</div></section><section className="panel"><h2>Latest 50 stock movements</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Product / location</th><th>Change</th><th>Reason</th></tr></thead><tbody>{movements.data?.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td>{m.products?.name} · {m.warehouses?.name}</td><td>{m.quantity}</td><td>{m.document_id?<Link href={'/documents/'+m.document_id}>{m.reason}</Link>:m.reason}</td></tr>)}</tbody></table></div></section></Workspace>;
}
