import { Workspace } from '@/components/workspace';
import { DateFilter,EmployeeSelect,Feedback } from '@/components/workforce';
import { workforceData } from '@/lib/workforce/access';
import { today,workDate,netHours } from '@/lib/workforce/validation';
import { saveAttendance } from '@/app/employees/actions';
export const dynamic='force-dynamic';
export default async function Attendance({searchParams}:{searchParams:Promise<{date?:string;state?:string;edit?:string}>}){
 const q=await searchParams;const date=workDate.safeParse(q.date).success?q.date!:today();const d=await workforceData(date);const selected=d.attendance.find(r=>r.id===q.edit);
 const local=(s:string|null)=>s?new Date(Date.parse(s)+330*60000).toISOString().slice(0,16):'';
 return <Workspace email={d.user.email}><header><p className="eyebrow">PEOPLE</p><h1>Attendance</h1><p>Daily attendance and recorded hours. Dates and times use Asia/Kolkata.</p></header><Feedback state={q.state}/><DateFilter date={date}/>{!(d.self||d.review)?<p>You do not have workforce access.</p>:<><section className="panel"><h2>{selected?'Edit attendance':'Record attendance'}</h2>{!d.employees.some(e=>e.active)?<p>No active employee record is linked to your account. Ask HR to add and link your employee record.</p>:<form action={saveAttendance} className="form-grid"><EmployeeSelect employees={d.employees} selected={selected?.employee_id}/><label>Work date<input type="date" name="work_date" required defaultValue={date} max={today()}/></label><label>Status<select name="status" defaultValue={selected?.status??'PRESENT'}>{(d.review?['PRESENT','REMOTE','HALF_DAY','ABSENT','LEAVE','HOLIDAY']:['PRESENT','REMOTE','HALF_DAY']).map(s=><option key={s}>{s}</option>)}</select></label><label>Break minutes<input name="break_minutes" type="number" min="0" max="1440" defaultValue={selected?.break_minutes??0} required/></label><label>Check in (IST)<input name="check_in" type="datetime-local" defaultValue={local(selected?.check_in)}/></label><label>Check out (IST)<input name="check_out" type="datetime-local" defaultValue={local(selected?.check_out)}/></label><label className="full">Notes<textarea name="notes" maxLength={2000} defaultValue={selected?.notes??''}/></label><p>Saving replaces this employee’s attendance for the selected date. HR records leave, holidays, and absence.</p><button>Save attendance</button></form>}</section><section className="panel"><h2>Attendance for {date}</h2><p>Up to 200 records. Missing entries are unrecorded, not automatically absent.</p><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Status</th><th>Check in</th><th>Check out</th><th>Net hours</th><th>Notes</th><th/></tr></thead><tbody>{d.attendance.map(r=><tr key={r.id}><td>{d.employees.find(e=>e.id===r.employee_id)?.name??'Staff record'}</td><td>{r.status}</td><td>{local(r.check_in).replace('T',' ')||'—'}</td><td>{local(r.check_out).replace('T',' ')||'—'}</td><td>{netHours(r.check_in,r.check_out,r.break_minutes)}</td><td>{r.notes}</td><td><a href={`/attendance?date=${date}&edit=${r.id}`}>Edit</a></td></tr>)}</tbody></table></div>{!d.attendance.length&&<p>No attendance recorded for this date.</p>}</section></>}</Workspace>;
}
