import { Workspace } from '@/components/workspace';
import { Feedback } from '@/components/workforce';
import { workforceAccess } from '@/lib/workforce/access';
import { saveEmployee,linkEmployee,setEmployeeActive } from './actions';
export const dynamic='force-dynamic';
export default async function Employees({searchParams}:{searchParams:Promise<{state?:string}>}){
 const access=await workforceAccess();const {db,user,organizationId,manage}=access;const {state}=await searchParams;
 if(!organizationId||!manage)return <Workspace email={user.email}><h1>Employee directory</h1><p>HR or administrator access is required to manage staff. Use Attendance and Daily work for your own records.</p></Workspace>;
 const {data,error}=await db.from('employees').select('*').eq('organization_id',organizationId).order('name').limit(200);if(error)throw new Error('Unable to load employees.');
 return <Workspace email={user.email}><header><p className="eyebrow">PEOPLE</p><h1>Employee directory</h1><p>Register staff, then link each employee to an existing workspace login for self-service attendance.</p></header><Feedback state={state}/><section className="panel"><h2>Add employee</h2><form action={saveEmployee} className="form-grid"><label>Employee number<input name="employee_number" required maxLength={40}/></label><label>Full name<input name="name" required minLength={2} maxLength={120}/></label><label>Department<input name="department" maxLength={100}/></label><label>Job title<input name="job_title" maxLength={100}/></label><button>Add employee</button></form></section><section className="panel"><h2>Staff ({data.length})</h2><p>Showing up to 200 staff. Linked accounts must already have active employee or management access in this workspace.</p>{!data.length&&<p>No employees yet. Add your first staff record above.</p>}{data.map(e=><article className="staff-row" key={e.id}><div><h3>{e.name} <span className="tag">{e.active?'Active':'Inactive'}</span></h3><p>{e.employee_number} · {e.department||'No department'} · {e.job_title||'No job title'}</p><p>{e.user_id?'Workspace login linked':'No login linked — HR can record attendance until an account is linked.'}</p></div><form action={linkEmployee}><input type="hidden" name="id" value={e.id}/><label>Workspace account email<input type="email" name="email" required placeholder="employee@company.com"/></label><button className="secondary">Link account</button></form><form action={setEmployeeActive}><input type="hidden" name="id" value={e.id}/><input type="hidden" name="active" value={String(!e.active)}/><button className="secondary">{e.active?'Deactivate':'Reactivate'}</button></form></article>)}</section></Workspace>;
}
