'use server';
import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {z} from 'zod';
import {operationsAccess,safeMessage} from '@/lib/operations/access';
async function admin(){const a=await operationsAccess();if(!a.admin||!a.organizationId)redirect('/dashboard');return {...a,organizationId:a.organizationId};}
function done(path:string,error?:{message:string}|null){if(error)redirect(path+'?error='+encodeURIComponent(safeMessage(error.message)));revalidatePath('/', 'layout');redirect(path+'?saved=1');}
export async function saveDocument(form:FormData){const a=await admin();const parsed=z.object({id:z.union([z.uuid(),z.literal('')]),kind:z.enum(['ORDER','QUOTE','PURCHASE']),party:z.uuid(),warehouse:z.uuid(),supply:z.string().regex(/^\d{2}$/),deadline:z.union([z.iso.date(),z.literal('')]),memo:z.string().max(2000)}).safeParse(Object.fromEntries(form));
 if(!parsed.success)redirect('/sales/orders?error=Check+required+document+fields');const v=parsed.data;const products=form.getAll('product_id'),quantities=form.getAll('quantity');const items=products.map((product_id,i)=>({product_id,quantity:quantities[i]})).filter(i=>i.product_id);
 const lines=z.array(z.object({product_id:z.uuid(),quantity:z.coerce.number().positive().max(1e8)})).min(1).max(100).safeParse(items);if(!lines.success)redirect('/sales/orders?error=Add+valid+product+lines');
 const r=await a.db.rpc('save_business_document',{org_id:a.organizationId,doc_id:v.id||null,doc_kind:v.kind,party_id:v.party,warehouse:v.warehouse,supply:v.supply,deadline:v.deadline||null,memo:v.memo,items:lines.data});done(r.data?'/documents/'+r.data:'/sales/orders',r.error);
}
export async function changeDocument(form:FormData){const a=await admin();const p=z.object({id:z.uuid(),command:z.enum(['APPROVE','DISPATCH','DELIVER','RECEIVE','CANCEL','MARK_SENT','ACCEPT','INVOICE'])}).safeParse(Object.fromEntries(form));if(!p.success)redirect('/dashboard');const r=await a.db.rpc('change_document_state',{org_id:a.organizationId,doc_id:p.data.id,command:p.data.command});done('/documents/'+(r.data||p.data.id),r.error);}
export async function adjustStock(form:FormData){const a=await admin();const p=z.object({warehouse:z.uuid(),product:z.uuid(),delta:z.coerce.number().finite().refine(v=>v!==0),reason:z.string().trim().min(5).max(500)}).safeParse(Object.fromEntries(form));if(!p.success)redirect('/inventory?error=Enter+a+quantity+and+explanation');const r=await a.db.rpc('record_stock_change',{org_id:a.organizationId,warehouse:p.data.warehouse,product:p.data.product,delta:p.data.delta,reason_text:p.data.reason});done('/inventory',r.error);}
export async function recordPayment(form:FormData){const a=await admin();const p=z.object({id:z.uuid(),amount:z.coerce.number().positive(),method:z.enum(['CASH','BANK_TRANSFER','UPI','CARD','CHEQUE','OTHER']),reference:z.string().trim().min(2).max(200),date:z.iso.date()}).safeParse(Object.fromEntries(form));if(!p.success)redirect('/finance?error=Check+payment+fields');const v=p.data;const r=await a.db.rpc('record_document_payment',{org_id:a.organizationId,doc_id:v.id,value:v.amount,payment_method:v.method,payment_reference:v.reference,payment_date:v.date});done('/documents/'+v.id,r.error);}
