import {Workspace} from '@/components/workspace';
import {operationsAccess} from '@/lib/operations/access';
import {saveChannel} from './actions';
export const dynamic='force-dynamic';
export default async function Integrations({searchParams}:{searchParams:Promise<{error?:string,saved?:string}>}){
 const a=await operationsAccess(),s=await searchParams;if(!a.admin||!a.organizationId)return <Workspace email={a.user.email}><h1>Administrator access required</h1></Workspace>;
 const [channels,events]=await Promise.all([a.db.from('messaging_channels').select('*').eq('organization_id',a.organizationId),a.db.from('integration_events').select('id,event_type,entity_id,created_at').eq('organization_id',a.organizationId).order('created_at',{ascending:false}).limit(50)]);if(channels.error||events.error)throw new Error('Unable to load integrations.');
 return <Workspace email={a.user.email}><header><p className="eyebrow">ADMINISTRATION</p><h1>Messaging integrations</h1><p>WhatsApp and Telegram are reserved for future activation. Orders continue to work independently of messaging.</p></header>{s.error&&<p className="notice" role="alert">{s.error}</p>}{s.saved&&<p role="status">Integration plan saved.</p>}<div className="grid">{(['WHATSAPP','TELEGRAM'] as const).map(channel=>{const config=channels.data.find(c=>c.channel===channel);return <section className="panel" key={channel}><h2>{channel==='WHATSAPP'?'WhatsApp Business':'Telegram bot'}</h2><p><strong>Not connected · Sending disabled</strong></p><p>{channel==='WHATSAPP'?'Future setup: Meta business number, approved templates and recipient consent.':'Future setup: BotFather bot, authorized staff group and linked customer accounts.'}</p><form action={saveChannel} className="form-grid"><input type="hidden" name="channel" value={channel}/><label>Intended recipient or team<input name="recipient_label" maxLength={160} defaultValue={config?.recipient_label||''}/></label><label>Setup notes<textarea name="notes" maxLength={1000} defaultValue={config?.notes||''}/></label><p>Do not enter passwords or API tokens. Credentials belong in server secret storage when the integration is activated.</p><button>Save plan</button></form></section>;})}</div><section className="panel"><h2>Latest 50 business events</h2><p>These events are recorded for future integration. No messages have been queued or sent.</p><div className="table-wrap"><table><thead><tr><th>Date</th><th>Event</th><th>Reference</th></tr></thead><tbody>{events.data.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td>{e.event_type}</td><td>{e.entity_id}</td></tr>)}</tbody></table></div>{!events.data.length&&<p>No events yet.</p>}</section></Workspace>;
}
