import Link from 'next/link';
import {Workspace} from '@/components/workspace';
import {operationsAccess} from '@/lib/operations/access';
import {money} from '@/lib/operations/config';
import {issueNote} from './actions';
export const dynamic='force-dynamic';
export default async function Notes({searchParams}:{searchParams:Promise<{page?:string,error?:string,saved?:string}>}){
 const a=await operationsAccess();if(!a.admin)return <Workspace email={a.user.email}><h1>Administrator access required</h1></Workspace>;
 const s=await searchParams;const page=Math.max(1,Math.min(10000,Math.floor(Number(s.page)||1)));
 const [notes,invoices]=await Promise.all([a.db.from('adjustment_notes').select('*',{count:'exact'}).eq('organization_id',a.organizationId).order('created_at',{ascending:false}).range((page-1)*50,page*50-1),a.db.from('business_documents').select('id,number,grand_total').eq('organization_id',a.organizationId).eq('kind','INVOICE').eq('state','ISSUED').order('created_at',{ascending:false}).limit(1000)]);
 if(notes.error||invoices.error)throw new Error('Unable to load adjustment records.');
 return <Workspace email={a.user.email}><header><p className="eyebrow">FINANCE / ADJUSTMENTS</p><h1>Credit & debit notes</h1><p>Issue traceable adjustments while preserving the original invoice.</p><Link href="/finance">View receivables & payables →</Link></header>{s.error&&<p className="notice" role="alert">{s.error}</p>}{s.saved&&<p className="notice" role="status">Adjustment issued. Invoice balances have been updated.</p>}<section className="panel"><h2>Issue an adjustment</h2><p>Credits reduce the unpaid invoice balance; debits increase it. Issued notes are permanent records. Refunds are not supported here.</p>{invoices.data?.length?<form action={issueNote} className="form-grid"><input type="hidden" name="request_key" value={crypto.randomUUID()}/><label className="full">Issued invoice<select name="invoice" required defaultValue=""><option value="" disabled>Select an invoice (latest 1,000)</option>{invoices.data.map(d=><option key={d.id} value={d.id}>{d.number} · {money(d.grand_total)}</option>)}</select></label><label>Adjustment type<select name="kind"><option value="CREDIT">Credit — reduce balance</option><option value="DEBIT">Debit — increase balance</option></select></label><label>Amount before tax<input type="number" name="amount" min="0.01" max="100000000000" step="0.01" required/></label><label>Tax amount<input type="number" name="tax" min="0" max="100000000000" step="0.01" defaultValue="0" required/></label><label className="full">Reason<textarea name="reason" minLength={5} maxLength={1000} required/></label><button type="submit">Issue adjustment</button></form>:<p>No issued invoices are available for adjustment.</p>}</section><section className="panel"><div className="section-heading"><h2>Adjustment register</h2><span className="tag">{notes.count||0} records</span></div><div className="table-wrap"><table><thead><tr><th>Note</th><th>Type</th><th>Date</th><th>Total</th><th>Reason</th><th>Invoice</th></tr></thead><tbody>{notes.data?.map(n=><tr key={n.id}><td>{n.note_number}</td><td>{n.note_type}</td><td>{n.issued_on}</td><td>{money(n.grand_total)}</td><td>{n.reason}</td><td><Link href={'/documents/'+n.invoice_id}>View invoice →</Link></td></tr>)}</tbody></table></div>{!notes.data?.length&&<p>No adjustments issued yet.</p>}<div className="inline-form">{page>1&&<Link href={'?page='+(page-1)}>Previous</Link>}{page*50<(notes.count||0)&&<Link href={'?page='+(page+1)}>Next</Link>}</div></section></Workspace>;
}
