import {Workspace} from '@/components/workspace';
import {operationsAccess} from '@/lib/operations/access';
import {money} from '@/lib/operations/config';
import {today} from '@/lib/workforce/validation';
import {z} from 'zod';
export const dynamic='force-dynamic';
export default async function Analytics({searchParams}:{searchParams:Promise<{from?:string,to?:string}>}){
 const a=await operationsAccess();if(!a.admin||!a.organizationId)return <Workspace email={a.user.email}><h1>Administrator analytics access required</h1></Workspace>;
 const s=await searchParams,date=today();const from=s.from||date.slice(0,4)+'-01-01',to=s.to||date;const valid=z.iso.date().safeParse(from).success&&z.iso.date().safeParse(to).success&&from<=to&&(Date.parse(to)-Date.parse(from))/86400000<=366;
 const result=valid?await a.db.rpc('management_metrics',{org_id:a.organizationId,period_start:from,period_end:to}):{data:null,error:null};if(result.error)throw new Error('Unable to load management metrics.');const m=result.data;
 return <Workspace email={a.user.email}><header><p className="eyebrow">BUSINESS INTELLIGENCE</p><h1>Management analytics</h1><p>Calculated from recorded transactions. Sales exclude tax. Receivables, payables, pipeline and stock reflect current balances.</p></header><section className="panel"><form method="get" className="form-grid"><label>Period start<input type="date" name="from" defaultValue={from} required/></label><label>Period end<input type="date" name="to" defaultValue={to} required/></label><button>Apply period</button></form>{!valid&&<p role="alert">Choose a valid period of at most 366 days.</p>}</section>{m&&<><div className="grid">{[['Invoiced sales',money(m.revenue)],['Sales GST',money(m.tax)],['Receivables',money(m.receivables)],['Overdue receivables',money(m.overdue)],['Payables',money(m.payables)],['Operating expenses',money(m.expenses)],['Stock at current catalog cost',money(m.stock_value)],['Production batches',m.production_batches]].map(([title,value])=><section className="panel" key={title}><p className="eyebrow">{title}</p><h2>{value}</h2></section>)}</div><section className="panel"><h2>Operational signals</h2><p>{m.low_stock} existing stock balances at or below reorder point · {m.overdue_followups} overdue lead follow-ups · {m.overdue_tasks} overdue tasks.</p><p>Stock value uses current catalog cost and is an operational estimate, not a statutory inventory valuation.</p></section><section className="panel"><h2>Monthly invoiced sales</h2><table><thead><tr><th>Month</th><th>Sales excluding tax</th><th>Invoices</th></tr></thead><tbody>{m.monthly.map((r:{month:string,revenue:number,invoices:number})=><tr key={r.month}><td>{r.month}</td><td>{money(r.revenue)}</td><td>{r.invoices}</td></tr>)}</tbody></table>{!m.monthly.length&&<p>No issued invoices in this period.</p>}</section><section className="panel"><h2>Current lead pipeline</h2><table><thead><tr><th>Stage</th><th>Leads</th><th>Expected value</th></tr></thead><tbody>{m.pipeline.map((r:{stage:string,count:number,value:number})=><tr key={r.stage}><td>{r.stage}</td><td>{r.count}</td><td>{money(r.value)}</td></tr>)}</tbody></table><p>Expected pipeline value is not booked revenue.</p></section></>}</Workspace>;
}
