import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {Workspace} from '@/components/workspace';
import {operationsAccess} from '@/lib/operations/access';
import {documentChoices} from '@/lib/operations/choices';
import {transferStock} from './actions';
export const dynamic='force-dynamic';
export default async function Transfers({searchParams}:{searchParams:Promise<{error?:string,saved?:string,page?:string}>}){
 const a=await operationsAccess(),s=await searchParams;const page=Math.max(1,Math.min(10000,Math.floor(Number(s.page)||1)));
 const result=await a.db.from('stock_transfers').select('*,products(name),source:warehouses!stock_transfers_organization_id_from_warehouse_fkey(name),destination:warehouses!stock_transfers_organization_id_to_warehouse_fkey(name)',{count:'exact'}).eq('organization_id',a.organizationId).order('created_at',{ascending:false}).range((page-1)*30,page*30-1);
 if(result.error)throw new Error('Unable to load transfers.');const choices=a.admin?await documentChoices(a,'ORDER'):null;
 return <Workspace email={a.user.email}><header><p className="eyebrow">WAREHOUSE</p><h1>Stock transfers</h1><p>Post completed physical transfers. Reserved stock cannot be transferred. Each transfer creates equal outbound and inbound movements.</p><Link href="/inventory">← Stock balances</Link></header>{s.error&&<p className="notice" role="alert">{s.error}</p>}{s.saved&&<p role="status">Transfer recorded.</p>}{choices&&<section className="panel"><form action={transferStock} className="form-grid"><label>From warehouse<select name="source" required><option value="">Select</option>{choices.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>To warehouse<select name="destination" required><option value="">Select</option>{choices.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Product<select name="product" required><option value="">Select</option>{choices.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Quantity<input type="number" name="quantity" min="0.001" max="100000000" step="0.001" required/></label><label>Unique transfer reference<input name="reference" defaultValue={'TR-'+randomUUID().slice(0,12)} minLength={3} maxLength={100} required/></label><label>Reason<input name="reason" minLength={5} maxLength={500} required/></label><button>Post completed transfer</button></form></section>}<section className="panel"><h2>Transfer history</h2><p>{result.count||0} transfers · Page {page}</p><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Product</th><th>From → To</th><th>Quantity</th><th>Reason</th></tr></thead><tbody>{result.data.map(r=><tr key={r.id}><td>{r.reference}</td><td>{r.products?.name}</td><td>{r.source?.name} → {r.destination?.name}</td><td>{r.quantity}</td><td>{r.reason}</td></tr>)}</tbody></table></div>{!result.data.length&&<p>No transfers yet.</p>}<div className="inline-form">{page>1&&<Link href={`?page=${page-1}`}>Previous</Link>}{page*30<(result.count||0)&&<Link href={`?page=${page+1}`}>Next</Link>}</div></section></Workspace>;
}
