import Link from 'next/link';
import {Workspace} from '@/components/workspace';
import {operationsAccess} from '@/lib/operations/access';
import {money} from '@/lib/operations/config';
import {reviewRequest} from './actions';
export const dynamic='force-dynamic';
export default async function Requests({searchParams}:{searchParams:Promise<{page?:string,status?:string,error?:string,saved?:string}>}){
 const a=await operationsAccess(),s=await searchParams;if(!a.admin||!a.organizationId)return <Workspace email={a.user.email}><h1>Administrator access required</h1></Workspace>;
 const page=Math.max(1,Math.min(10000,Math.floor(Number(s.page)||1)));const status=['SUBMITTED','IN_REVIEW','ACCEPTED','REJECTED','RESOLVED'].includes(s.status||'')?s.status:'SUBMITTED';
 const [requests,warehouses]=await Promise.all([a.db.from('portal_requests').select('*,customers(name)',{count:'exact'}).eq('organization_id',a.organizationId).eq('status',status).order('created_at',{ascending:false}).range((page-1)*30,page*30-1),a.db.from('warehouses').select('id,name').eq('organization_id',a.organizationId).eq('active',true).order('name').limit(1000)]);
 if(requests.error||warehouses.error)throw new Error('Unable to load review queue.');
 return <Workspace email={a.user.email}><header><p className="eyebrow">CUSTOMER SERVICE</p><h1>Portal requests</h1><p>Review dealer and customer submissions. Accepting an order creates a draft at current catalog prices; approval, credit checks and stock reservation happen in the order workflow.</p></header>{s.error&&<p className="notice" role="alert">{s.error}</p>}{s.saved&&<p role="status">Review saved.</p>}<form className="inline-form"><label>Status<select name="status" defaultValue={status}>{['SUBMITTED','IN_REVIEW','ACCEPTED','REJECTED','RESOLVED'].map(v=><option key={v}>{v}</option>)}</select></label><button>Filter</button></form><p>{requests.count||0} requests · Page {page}</p>{requests.data.map(r=><section className="panel" key={r.id}><h2>{r.subject}</h2><p>{r.customers?.name} · {r.kind} · {r.status}</p><p>{r.details}</p>{r.kind==='ORDER'&&<><p>Submitted estimate: {money(r.estimated_total)}</p><ul>{r.items.map((l:{product_id:string,name:string,quantity:number,unit:string})=><li key={l.product_id}>{l.name}: {l.quantity} {l.unit}</li>)}</ul></>}{r.admin_reply&&<p>Response: {r.admin_reply}</p>}{r.document_id&&<Link href={'/documents/'+r.document_id}>Open ERP order →</Link>}{['SUBMITTED','IN_REVIEW'].includes(r.status)&&<form action={reviewRequest} className="form-grid"><input type="hidden" name="id" value={r.id}/><label>Decision<select name="status"><option value="IN_REVIEW">In review</option>{r.kind==='ORDER'?<option value="ACCEPTED">Accept and create draft order</option>:<option value="RESOLVED">Resolve request</option>}<option value="REJECTED">Reject</option></select></label><label>Response shown to customer<textarea name="reply" maxLength={2000} defaultValue={r.admin_reply}/></label>{r.kind==='ORDER'?<><label>Warehouse (required to accept)<select name="warehouse"><option value="">Select warehouse</option>{warehouses.data.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Place of supply state code<input name="supply" pattern="[0-9]{2}" maxLength={2} placeholder="e.g. 37"/></label></>:<><input type="hidden" name="warehouse" value=""/><input type="hidden" name="supply" value=""/></>}<button>Save review</button></form>}</section>)}{!requests.data.length&&<p className="panel">No requests with this status.</p>}<div className="inline-form">{page>1&&<Link href={`?status=${status}&page=${page-1}`}>Previous</Link>}{page*30<(requests.count||0)&&<Link href={`?status=${status}&page=${page+1}`}>Next</Link>}</div></Workspace>;
}
