import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Workspace} from '@/components/workspace';
import {RecordForm,Option} from '@/components/operations/record-form';
import {modules} from '@/lib/operations/config';
import {operationsAccess} from '@/lib/operations/access';
export const dynamic='force-dynamic';
export default async function Records({params,searchParams}:{params:Promise<{module:string}>,searchParams:Promise<{page?:string,q?:string,error?:string,saved?:string}>}){
 const {module:slug}=await params;const config=Object.hasOwn(modules,slug)?modules[slug]:null;if(!config)notFound();
 const {db,user,organizationId,admin}=await operationsAccess();const search=await searchParams;const page=Math.min(10000,Math.max(1,Number(search.page)||1));const q=(search.q||'').slice(0,100).replaceAll('%','').replaceAll('_','');
 if(!organizationId)return <Workspace email={user.email}><h1>Access awaiting assignment</h1></Workspace>;
 let query=db.from(config.table).select('*',{count:'exact'}).eq('organization_id',organizationId).order('created_at',{ascending:false}).range((page-1)*25,page*25-1);if(q)query=query.ilike('name','%'+q+'%');
 const {data,error,count}=await query;if(error)throw new Error('Unable to load records.');
 const options:Record<string,Option[]>={};if(admin){for(const relation of new Set(config.fields.flatMap(f=>f.relation?[f.relation]:[]))){const result=relation==='members'?await db.rpc('admin_members',{org_id:organizationId}):relation==='business_documents'?await db.from(relation).select('id,number').eq('organization_id',organizationId).eq('kind','ORDER').in('state',['APPROVED','DISPATCHED','DELIVERED']).order('created_at',{ascending:false}).limit(1000):await db.from(relation).select('id,name').eq('organization_id',organizationId).order('name').limit(1000);if(result.error)throw new Error('Unable to load available choices.');options[relation]=(result.data||[]).map((r:Record<string,unknown>)=>({id:String(r.id||r.user_id),name:String(r.name||r.number||r.email)}));}}
 return <Workspace email={user.email}><header><p className="eyebrow">OPERATIONS</p><h1>{config.title}</h1><p>{config.description}</p></header>{search.error&&<p role="alert" className="notice">{search.error}</p>}{search.saved&&<p role="status">Saved successfully.</p>}{admin&&<details className="panel"><summary>Add {config.title.toLowerCase()} record</summary><RecordForm slug={slug} options={options}/></details>}<section className="panel"><form method="get" className="inline-form"><label>Search by name<input name="q" defaultValue={q}/></label><button className="secondary">Search</button></form><p>{count||0} visible records · Page {page}{!admin?' · Read-only access':''}</p>{!data.length&&<p>No records available.</p>}{data.map(row=><article className="staff-row" key={row.id}><h3>{row.name}</h3><dl className="record-values">{config.fields.filter(f=>!f.relation&&f.key!=='name').map(f=><div key={f.key}><dt>{f.label}</dt><dd>{String(row[f.key]??'—')}</dd></div>)}</dl>{admin&&<details><summary>Edit record</summary><RecordForm slug={slug} record={row} options={options}/></details>}</article>)}<div className="inline-form">{page>1&&<Link href={`?page=${page-1}&q=${encodeURIComponent(q)}`}>Previous</Link>}{page*25<(count||0)&&<Link href={`?page=${page+1}&q=${encodeURIComponent(q)}`}>Next</Link>}</div></section></Workspace>;
}
