export const dynamic='force-dynamic';
import Link from 'next/link';
import {visibleNavigation} from '@/lib/navigation';
import {redirect} from 'next/navigation';
import {operationsAccess} from '@/lib/operations/access';
import {Workspace} from '@/components/workspace';
export default async function Dashboard(){const a=await operationsAccess();const {db,user,organizationId,role,admin}=a;if(organizationId&&['CUSTOMER','DEALER','DISTRIBUTOR'].includes(role||''))redirect('/portal');if(!organizationId)return <Workspace email={user.email}><h1>Access awaiting assignment</h1><p>An administrator must assign your workspace and role.</p></Workspace>;
 const company=await db.from('company_settings').select('display_name').eq('organization_id',organizationId).single();if(company.error)throw new Error('Unable to load workspace.');
 const permissions=await db.from('role_permissions').select('permission_code').eq('role_code',role);if(permissions.error)throw new Error('Unable to load permissions.');const allowed=(path:string)=>visibleNavigation([[path,'']],permissions.data.map(p=>p.permission_code),role).length>0;const cards=[{table:'leads',title:'Lead pipeline',path:'/records/leads'},{table:'customers',title:'Customers & dealers',path:'/records/customers'},{table:'business_documents',title:'Business documents',path:'/sales/orders'},{table:'business_tasks',title:'Assigned tasks',path:'/records/tasks'}].filter(c=>allowed(c.path));const counts=await Promise.all(cards.map(c=>db.from(c.table).select('id',{count:'exact',head:true}).eq('organization_id',organizationId)));if(counts.some(c=>c.error))throw new Error('Unable to load workspace overview.');
 return <Workspace email={user.email}><header className="dashboard-hero"><div className="hero-grid" aria-hidden="true"/><p className="eyebrow">BUSINESS WORKSPACE</p><h1>{company.data.display_name}</h1><p>CRM, sales, purchasing, inventory and your team in one place.</p><span className="tag">{role?.replaceAll('_',' ')}</span></header><div className="grid metrics-grid">{cards.map((c,i)=><section className="panel metric-card" key={c.table}><p className="eyebrow">{c.title}</p><h2>{counts[i].count||0}</h2><p>Records visible with your access.</p><Link href={c.path}>Open {c.title.toLowerCase()} →</Link></section>)}</div>{admin&&<section className="panel"><h2>Set up your operations</h2><ol><li><Link href="/settings/company">Complete company details</Link> for invoice generation.</li><li><Link href="/admin/users">Invite users</Link>, then <Link href="/employees">add and link employees</Link>.</li><li><Link href="/records/products">Add products</Link>, <Link href="/records/warehouses">warehouses</Link> and <Link href="/inventory">opening stock</Link>.</li><li><Link href="/records/customers">Create customers and their credit limits</Link>, then start a quotation or order.</li></ol></section>}{allowed('/attendance')&&<section className="panel"><h2>Your working day</h2><div className="inline-form"><Link href="/attendance">Attendance →</Link><Link href="/work-logs">Daily work →</Link><Link href="/records/tasks">Assigned tasks →</Link></div></section>}<section className="panel"><h2>Business records stay accountable</h2><p>Admins manage records and access. Other users see records permitted by their role, and employees record their own attendance and work. Changes are retained in audit history.</p>{allowed('/audit')&&<Link href="/audit">Audit history →</Link>}</section></Workspace>;
}
