begin;
create table public.adjustment_notes(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),note_number text not null,note_type text not null check(note_type in ('CREDIT','DEBIT')),invoice_id uuid not null,reason text not null check(length(reason) between 5 and 1000),amount numeric(16,2) not null check(amount>0),tax_amount numeric(16,2) not null default 0,grand_total numeric(16,2) not null,state text not null default 'ISSUED' check(state in ('ISSUED','CANCELLED')),issued_on date not null default current_date,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),unique(organization_id,note_number),foreign key(organization_id,invoice_id) references public.business_documents(organization_id,id));
alter table public.adjustment_notes enable row level security;revoke all on public.adjustment_notes from public,anon,authenticated;grant select on public.adjustment_notes to authenticated;
create policy adjustment_notes_read on public.adjustment_notes for select to authenticated using(public.is_admin(organization_id) or public.has_permission(organization_id,'finance.view'));
create function public.issue_adjustment_note(org_id uuid,invoice uuid,note_kind text,note_amount numeric,note_tax numeric,note_reason text) returns uuid language plpgsql security definer set search_path='' as $$declare doc public.business_documents;note_id uuid;seq bigint;begin
 if auth.uid() is null or not public.is_admin(org_id) then raise exception 'Admin required';end if;
 if note_kind not in ('CREDIT','DEBIT') or note_amount is null or note_amount<=0 or note_tax is null or note_tax<0 or length(trim(note_reason))<5 then raise exception 'Invalid adjustment note';end if;
 perform 1 from public.organizations where id=org_id for update;select * into doc from public.business_documents where id=invoice and organization_id=org_id and kind='INVOICE' and state='ISSUED' for update;if not found then raise exception 'Issued invoice required';end if;
 if note_amount+note_tax>doc.grand_total then raise exception 'Adjustment exceeds invoice total';end if;
 insert into public.document_counters(organization_id,kind,number) values(org_id,note_kind,1) on conflict(organization_id,kind) do update set number=document_counters.number+1 returning number into seq;
 insert into public.adjustment_notes(organization_id,note_number,note_type,invoice_id,reason,amount,tax_amount,grand_total,created_by) values(org_id,case note_kind when 'CREDIT' then 'SP/CR/' else 'SP/DR/' end||to_char(current_date,'YYYY')||'/'||lpad(seq::text,6,'0'),note_kind,invoice,note_reason,note_amount,note_tax,note_amount+note_tax,auth.uid()) returning id into note_id;
 insert into public.audit_logs(organization_id,actor_id,action,entity,entity_id,after_value) values(org_id,auth.uid(),'ISSUE','adjustment_notes',note_id,jsonb_build_object('invoice',invoice,'type',note_kind,'amount',note_amount,'tax',note_tax));return note_id;end$$;
revoke all on function public.issue_adjustment_note(uuid,uuid,text,numeric,numeric,text) from public,anon;grant execute on function public.issue_adjustment_note(uuid,uuid,text,numeric,numeric,text) to authenticated;commit;
